export const actionTypes = {
  ADD_LIST_REQUEST: 'ADD_LIST_REQUEST',
  ADD_LIST_SUCCESS: 'ADD_LIST_SUCCESS',
  ADD_LIST_FAILURE: 'ADD_LIST_FAILURE',
  GET_LISTS_REQUEST: 'GET_LISTS_REQUEST',
  GET_LISTS_SUCCESS: 'GET_LISTS_SUCCESS',
  GET_LISTS_FAILURE: 'GET_LISTS_FAILURE',
};

export type Action = { type: string, payload?: any };
